import React from 'react'
import Head from 'next/head'
import { EditorTemplate } from '../components/templates/EditorTemplate'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Title</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <EditorTemplate />
      </main>

      <footer style={{ paddingTop: '1.5rem', textAlign: 'center' }}>
        <a href="" target="_blank" rel="noopener noreferrer">
          Powered by unvalley
        </a>
      </footer>
    </div>
  )
}
